namespace Microservices.Foundation.ContentTypes.Enums
{
    public enum ControlTypes
    {
        TextField,
        RichTextField,
        LocalizedRichTextField,
        LocalizedTextField,
        MultilineTextField,
        LocalizedMultilineTextField,
        Switch,
        Calendar,
        RangeCalender,
        Clock,
        TimeRange,
        Time,
        Link,
        Numeric,
        QR,
        Cards,
        List,
        ListSearch,
        POSSelector,
        Checker,
        Media,
        Dynamic,
        Undefined
    }
}
